version: '3'

services:
  # db:
  #   image: postgres:latest
  #   container_name: bot_postgres
  #   env_file:
  #     - .env
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data
  #     - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

  bot:
    build:
      context: ./bot
    container_name: bot
    # depends_on:
    #   - db
    env_file:
      - .env

volumes:
  postgres_data:
